Una vez firmado el contrato. Se tienen que ir archivando una base de datos del cliente, con la información del proceso, consumo, precio contratado, etc.

## Librerías

In [4]:
import pandas as pd
from pandas import ExcelWriter
from pandas import ExcelFile
import seaborn as sns

## Calling Excel

In [5]:
clientes = pd.read_excel("../Data/BD_Clientes.xlsx", engine='openpyxl')
clientes

,Cliente:,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Establecimiento:,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 90,Unnamed: 91,Unnamed: 92,Unnamed: 93,Unnamed: 94,Unnamed: 95,Unnamed: 96,Estatus de cliente:,Unnamed: 98,Unnamed: 99
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Información del cliente,NaN,NaN,NaN,NaN,Información del establecimiento,NaN,NaN,NaN,NaN,...,NaN,Ahorro final,NaN,NaN,NaN,NaN,NaN,Seguimiento de clientes,NaN,NaN
2,Cliente,Titular de la Cuenta,CIF / NIF,E-mail,Telefono,Codigo Cups,Dirección completa,Calle,Numero,Piso,...,Posible penalización (€),€,%,Comision Vivolt Teórica,Comision Vivolt Real,Alta cliente Vivolt,Alta cliente nueva comercializadora,1,2,Renovación de terminos
3,Cliente,Titular de la Cuenta,CIF / NIF,E-mail,Telefono,Codigo Cups,NaN,Calle,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,2,Renovación de terminos
4,La Estrella,"Azaya, S.L.",B28350619,NaN,686 937 963,ES0021000007463134RE,"Cmno Estrella Torre Tolanca, Km 7,5, 45100 Son...",NaN,NaN,NaN,...,0,3246.42,0.286958,750.706,NaN,NaN,None,1900-05-31 00:00:00,1900-10-30 00:00:00,1900-09-30 00:00:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93,Jimena Lopez de la Serna,Jayga Inversiones S.A.,B84257567,NaN,915934070,ES0021000015678558GF,"C/ GUECHO, 12 28023 MADRID",NaN,NaN,NaN,...,-506.904,2864.57,0.146876,1185.77,NaN,2020-11-30 00:00:00,2020-12-07 00:00:00,2021-05-08 00:00:00,2021-10-07 00:00:00,2021-09-07 00:00:00
94,Fernando Olazabal - Lavanderías,DYNASET AEREA AIE,V02645208,f.olazabal@dynaset.es,NaN,ES0021000003944940XT,"POLIGONO COMPISA (M-108) 4 BAJO, AJALVIR 28864...",NaN,NaN,NaN,...,-211.229,5266.82,0.284876,103.459,NaN,None,None,None,None,None
95,Sonia Casado,VACIASILOS 05 S.L,B84535327,soniacasado@pincasa.com,914410315,ES0021000005505634QY,"C/ FINCA LA VEGUILLA, S/N, Bajo 28320 PINTO (M...",NaN,NaN,NaN,...,-88.26,529.736,0.180258,73.1808,NaN,2020-12-04 00:00:00,2020-12-15 00:00:00,2021-05-16 00:00:00,2021-10-15 00:00:00,2021-09-15 00:00:00
96,Sonia Casado,VACIASILOS 05 S.L,B84535327,NaN,NaN,ES0021000005494251GP,"C/ FINCA LA VEGUILLA, S/N 28320 PINTO (MADRID)",NaN,NaN,NaN,...,-190.006,945.164,0.14191,97.6012,NaN,2020-12-04 00:00:00,2020-12-15 00:00:00,2021-05-16 00:00:00,2021-10-15 00:00:00,2021-09-15 00:00:00
97,Sonia Casado,VACIASILOS 05 S.L,B84535327,NaN,NaN,ES0022000008548093YS,"Ctra SAN MARTIN DE LA VEGA, 4 28320 PINTO (MAD...",NaN,NaN,NaN,...,-57.5582,371.705,0.147839,29.4601,NaN,2020-12-04 00:00:00,2020-12-15 00:00:00,2021-05-16 00:00:00,2021-10-15 00:00:00,2021-09-15 00:00:00

## DF a SQL