## Librerias

In [1]:
import pandas as pd
from pandas import ExcelWriter
from pandas import ExcelFile
import seaborn as sns

## Calling Excel

In [23]:
precio_fijo_df = pd.read_excel("../Data/BD_Precios_Fijos.xlsx", engine='openpyxl')

In [24]:
precio_fijo_df

,Comercializadora,Tarifa,Precio_Potencia_P1,Precio_Potencia_P2,Precio_Potencia_P3,Precio_Potencia_P4,Precio_Potencia_P5,Precio_Potencia_P6,Precio_Energía_P1,Precio_Energía_P2,Precio_Energía_P3,Precio_Energía_P4,Precio_Energía_P5,Precio_Energía_P6,Fecha Inicio,Fecha Finalización
0,CYE,2.0. A,38.043426,38.043426,38.043426,38.043426,38.043426,38.043426,0.109125,0.109125,0.109125,0.109125,0.109125,0.109125,16.11.2020,NaN
1,CYE,2.0. DHA,38.043426,38.043426,38.043426,38.043426,38.043426,38.043426,0.130285,0.056347,NaN,0.130285,0.056347,NaN,16.11.2020,NaN
2,CYE,2.1. A,44.444710,44.444710,44.444710,44.444710,44.444710,44.444710,0.122458,0.122458,0.122458,0.122458,0.122458,0.122458,16.11.2020,NaN
3,CYE,2.1. DHA,44.444710,44.444710,44.444710,44.444710,44.444710,44.444710,0.142841,0.067324,NaN,0.142841,0.067324,NaN,16.11.2020,NaN
4,CYE,3.0. A,40.728885,24.437330,16.291555,40.728885,24.437330,16.291555,0.092978,0.078824,0.055671,0.092978,0.078824,0.055671,16.11.2020,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
157,Opcion,2.0. DHA,38.043426,38.043426,38.043426,38.043426,38.043426,38.043426,151.545000,79.372000,NaN,151.545000,79.372000,NaN,01.03.2020,01.04.2019
158,Opcion,2.1. A,44.444710,44.444710,44.444710,44.444710,44.444710,44.444710,145.133000,145.133000,145.133000,145.133000,145.133000,145.133000,01.03.2020,01.04.2019
159,Opcion,2.1. DHA,44.444710,44.444710,44.444710,44.444710,44.444710,44.444710,164.125000,90.374000,NaN,164.125000,90.374000,NaN,01.03.2020,01.04.2019
160,Opcion,3.0. A,40.728885,24.437330,16.291555,40.728885,24.437330,16.291555,112.716000,99.748000,77.396000,112.716000,99.748000,77.396000,01.03.2020,01.04.2019
161,Opcion,3.1. A,59.173468,36.490689,8.367731,59.173468,36.490689,8.367731,98.272000,92.252000,75.045000,98.272000,92.252000,75.045000,01.03.2020,01.04.2019

## Exploring Data

In [11]:
precio_fijo_df.dtypes

Comercializadora       object
Tarifa                 object
Precio_Potencia_P1    float64
Precio_Potencia_P2    float64
Precio_Potencia_P3    float64
Precio_Potencia_P4    float64
Precio_Potencia_P5    float64
Precio_Potencia_P6    float64
Precio_Energía_P1     float64
Precio_Energía_P2     float64
Precio_Energía_P3     float64
Precio_Energía_P4     float64
Precio_Energía_P5     float64
Precio_Energía_P6     float64
Fecha Inicio           object
Fecha Finalización     object
dtype: object

In [12]:
precio_fijo_df.isna().sum()

Comercializadora        0
Tarifa                  0
Precio_Potencia_P1      0
Precio_Potencia_P2    108
Precio_Potencia_P3    108
Precio_Potencia_P4      0
Precio_Potencia_P5    108
Precio_Potencia_P6    108
Precio_Energía_P1       0
Precio_Energía_P2       0
Precio_Energía_P3      54
Precio_Energía_P4       0
Precio_Energía_P5       0
Precio_Energía_P6      54
Fecha Inicio            0
Fecha Finalización     24
dtype: int64

In [13]:
precio_fijo_df.describe()

,Precio_Potencia_P1,Precio_Potencia_P2,Precio_Potencia_P3,Precio_Potencia_P4,Precio_Potencia_P5,Precio_Potencia_P6,Precio_Energía_P1,Precio_Energía_P2,Precio_Energía_P3,Precio_Energía_P4,Precio_Energía_P5,Precio_Energía_P6
count,162.000000,54.000000,54.000000,162.000000,54.000000,54.000000,162.000000,162.000000,108.000000,162.000000,162.000000,108.000000
mean,44.146416,30.464010,12.329643,44.146416,30.464010,12.329643,68.984261,53.953136,54.680046,68.984261,53.953136,54.680046
std,7.235367,6.083269,3.999114,7.235367,6.083269,3.999114,64.389807,51.825854,54.600175,64.389807,51.825854,54.600175
min,38.043260,24.437330,8.367730,38.043260,24.437330,8.367730,0.073881,0.056155,0.052844,0.073881,0.056155,0.052844
25%,38.043426,24.437330,8.367731,38.043426,24.437330,8.367731,0.122916,0.077406,0.103692,0.122916,0.077406,0.103692
50%,42.586800,30.464010,12.329643,42.586800,30.464010,12.329643,91.552500,69.821000,58.538500,91.552500,69.821000,58.538500
75%,44.444710,36.490689,16.291555,44.444710,36.490689,16.291555,130.125000,92.048000,111.543000,130.125000,92.048000,111.543000
max,59.173470,36.490690,16.291560,59.173470,36.490690,16.291560,165.293000,146.540000,146.540000,165.293000,146.540000,146.540000

In [14]:
sns.pairplot(precio_fijo_df)

NameError: name 'sns' is not defined

In [15]:
precio_fijo_df.corr()

,Precio_Potencia_P1,Precio_Potencia_P2,Precio_Potencia_P3,Precio_Potencia_P4,Precio_Potencia_P5,Precio_Potencia_P6,Precio_Energía_P1,Precio_Energía_P2,Precio_Energía_P3,Precio_Energía_P4,Precio_Energía_P5,Precio_Energía_P6
Precio_Potencia_P1,1.000000,1.000000,-1.000000,1.000000,1.000000,-1.000000,-0.108142,-0.044590,-0.160228,-0.108142,-0.044590,-0.160228
Precio_Potencia_P2,1.000000,1.000000,-1.000000,1.000000,1.000000,-1.000000,-0.080763,-0.045037,-0.020543,-0.080763,-0.045037,-0.020543
Precio_Potencia_P3,-1.000000,-1.000000,1.000000,-1.000000,-1.000000,1.000000,0.080763,0.045037,0.020543,0.080763,0.045037,0.020543
Precio_Potencia_P4,1.000000,1.000000,-1.000000,1.000000,1.000000,-1.000000,-0.108142,-0.044590,-0.160228,-0.108142,-0.044590,-0.160228
Precio_Potencia_P5,1.000000,1.000000,-1.000000,1.000000,1.000000,-1.000000,-0.080763,-0.045037,-0.020543,-0.080763,-0.045037,-0.020543
Precio_Potencia_P6,-1.000000,-1.000000,1.000000,-1.000000,-1.000000,1.000000,0.080763,0.045037,0.020543,0.080763,0.045037,0.020543
Precio_Energía_P1,-0.108142,-0.080763,0.080763,-0.108142,-0.080763,0.080763,1.000000,0.912435,0.975537,1.000000,0.912435,0.975537
Precio_Energía_P2,-0.044590,-0.045037,0.045037,-0.044590,-0.045037,0.045037,0.912435,1.000000,0.989532,0.912435,1.000000,0.989532
Precio_Energía_P3,-0.160228,-0.020543,0.020543,-0.160228,-0.020543,0.020543,0.975537,0.989532,1.000000,0.975537,0.989532,1.000000
Precio_Energía_P4,-0.108142,-0.080763,0.080763,-0.108142,-0.080763,0.080763,1.000000,0.912435,0.975537,1.000000,0.912435,0.975537
Precio_Energía_P5,-0.044590,-0.045037,0.045037,-0.044590,-0.045037,0.045037,0.912435,1.000000,0.989532,0.912435,1.000000,0.989532
Precio_Energía_P6,-0.160228,-0.020543,0.020543,-0.160228,-0.020543,0.020543,0.975537,0.989532,1.000000,0.975537,0.989532,1.000000

In [16]:
precio_fijo_df["Comercializadora"].unique()

array(['CYE', 'Sun_Air_One', 'Audax', 'Opcion'], dtype=object)

In [17]:
precio_fijo_df["Tarifa"].unique()

array(['2.0. A', '2.0. DHA', '2.1. A', '2.1. DHA', '3.0. A', '3.1. A'],
      dtype=object)

In [20]:
precio_fijo_df["Fecha Inicio"].unique()

array(['16.11.2020', '11.06.2020', '08.09.2020', '05.08.2020',
       '17.11.2020', '01.12.2020', '03.11.2020', '05.10.2020',
       '06.07.2020', '01.05.2020', '01.04.2020', '01.03.2020',
       '01.02.2020', '01.01.2020', '01.12.2019', '01.11.2019',
       '01.10.2019', '01.09.2019', '01.08.2019', '01.07.2019',
       '01.06.2019', '01.05.2019', '01.04.2019'], dtype=object)

In [21]:
precio_fijo_df["Fecha Finalización"].unique()

array([nan, '16.11.2020', '08.09.2020', '17.11.2020', '01.12.2020',
       '03.11.2020', '05.10.2020', '05.08.2020', '06.07.2020',
       '11.06.2020', '01.05.2020', '01.04.2020', '01.03.2020',
       '01.02.2020', '01.01.2020', '01.12.2019', '01.11.2019',
       '01.10.2019', '01.09.2019', '01.08.2019', '01.07.2019',
       '01.06.2019', '01.05.2019', '01.04.2019'], dtype=object)

## Cleaning Data

#### Changing Column Names

I change the column name to match the other price dataframe.

In [ ]:
precio_fijo_df["Fecha Finalización"] = precio_fijo_df["Fecha_Finalización"]

In [ ]:
precio_fijo_df["Fecha Inicio"] = precio_fijo_df["Fecha_Inicio"]

#### Managing NaN

First we substitue the Price NaNs for value 0, as the price for that period is 0.

Then we create a function that adds the NaN values of Fecha_Finalización with the last date from the column Fecha_Inicio grouping_by the same column "Comercializadora"

#### Changing all "Precio" columns values  that are  MWh/€ to KWh/€

All values higher than 0 we divide by 1000 to transform to KWh.